create table payments (
                          id bigint generated by default as identity primary key,
                          amount numeric(19,2) not null,
                          currency varchar(3) not null,
                          description varchar(255),
                          status varchar(20) not null,
                          created_at timestamp not null
);
