create table customer (
                          id bigint generated by default as identity primary key,
                          email varchar(255) not null unique,
                          full_name varchar(255) not null,
                          created_at timestamp not null
);